language: node_js
node_js:
- 10.15.3
sudo: required
services:
- docker
before_install:
- docker build -t shashi2030/rick-server -f Dockerfile.dev .
script:
- docker run -e CI=true shashi2030/rick-server
- true
deploy:
  provider: heroku
  api_key:
    secure: cRL3SUvUp/uTHdVjF/Rpv/JM9KPSVge4Mtkl9P+jTH+0Dkk3YHwIzd7soqELDaKIKo9wgPM/D6vlDuF5iTcVJp0SRLs3omY8C0S1d4CsVLlPycYiuwXAwP3T62niHpp13iszvpULn+TuUgs+p0vo3wIp3sh7WfPUP0lSeKSJzF1c+cTQbB/rmfpDSPoXHMKmTu/u2f3Ik/ADjJ4+bB93VHLqvAPWd2OnPJs7AVhYiQcPLU5vA1MYxeGvoFeaIeS7ETC87WR8lvew97FwEv99cLD0OT+FLVC2ssEsGEOcLax+85votGvqvdpkdN19VExm8mQ5aha1o8W18biK04bKKXZ5E4EWPGml5Due1Fp3BIjaYkNFDx8YByrRUwYiX+twgh5bv4pK9PMSvf7tDbAAj36qQ8sNsjC9TJ9T3yo0qmij1a2F2l11EvJPr+j1V/s1cArKEQOTWZguepPDtVED/ZAZzYL272DBwir2p9um2OBNvLWnfDv1hLYDtJ7YWCkzWPEtR3s64pMxHaklqUkvNeBK0mHzksk0twNepeygOCEFqI+eYt1ZOAt0ZyC3tvwPU1caF2E9EQOmmVaKQ7PouCD3dITykJZ6Tj89EmrUSta/cwyo1Rz2eKqj6wl1dWHdzdWhOEdQqNF7um4oePPGzrPLB4GOXTyL9jd5/EKz0ic=
  skip_cleanup: true
  app: rick-server
  on:
    repo: shashi2030/rick-server
