language: node_js
node_js:
- 10.15.3
sudo: required
services:
- docker
before_install:
- docker build -t shashi2030/rick-server -f Dockerfile.dev .
script:
- docker run -e CI=true shashi2030/rick-server
- true
deploy:
  provider: heroku
  api_key:
    secure: C24Ja7qIQNjW1IJ5nXc+EHU7Ffn1nferEEb7uVw1iPWTuX9RLjEgEfrpcPyfwJ+rK/UgTIaYd0TPFp+pgMTYvCvR7RJfZ8r6xNNEV8axcCFgr++h+QO/MtiGoo53y3yTWCA5oXOeaGKNtJKb0Gcchfu1GH48J0kC9U3ACd8JFvd4vVANDXeZjTsYdVMbHNzIeb/KIg7zOUibJ07mxc5h+XwRJvwtXFaHfpWk8wy1z6pvdmr5nWa32VlkTTVk5GR5e3zWiePw/rorUti8fy2vNO95fM05cLRMpsj8zWgAVPAF4oL1rHb1FqUboTAfC0Dm83KOkOxTQGbBN8GIbTrUL/xpQd42YIQdXqVyYvRpibDiyR67l0UNZd5X3g0t/U7izZeHbLby937ZLvciPhjeD9RvrJnVbAgcZF1JAVxXlq72DlTJeP3WmirQMoZzdtc2ISe/PF8dGtTGinnklHdbT9qZ6A2zGjgQkRnQkw07ZWCTF6rF90i36p80oVR8Am+0GqNQpEPxuIbh4gYN5iYK5xrjNxwWWQAhCJAfnprwSDqsZa/kpNjVzapteuQ7/jIZyTL6nUGYdvHjVEr2AYYeT4U1YtKrehI54TGEOlXfNwar/2GvvWpORHekZ+UOuVwfJMRGA1KVnChSKNPsZErkbMdevncfWryEW9ldlnWuM8I=
  skip_cleanup: true
  app: rick-server
  on:
    repo: shashi2030/rick-server
